#!/bin/sh
cd ${0%/*} || exit 1

sh ../prepare_h2_model_assets.sh || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=dfLowMachFoam

runApplication blockMesh
runApplication decomposePar -force
runApplication mpirun -np 4 --allow-run-as-root $application -parallel
