#!/bin/sh
cd ${0%/*} || exit 1

sh ../prepare_h2_model_assets.sh || exit 1

if [ ! -f h2_full_inference_wrapper.onnx ]; then
    echo "ONNX wrapper not found. Building h2_full_inference_wrapper.onnx ..."
    python3 ./build_h2_onnx_wrapper.py . ./h2_full_inference_wrapper.onnx || exit 1
fi

if [ ! -f h2_full_inference_wrapper_fp32.plan ]; then
    echo "TensorRT engine not found. Building h2_full_inference_wrapper_fp32.plan ..."
    ./build_h2_tensorrt_engine.sh || exit 1
fi

. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=dfLowMachFoam

runApplication blockMesh
runApplication decomposePar -force
runApplication mpirun -np 4 --allow-run-as-root $application -parallel
